services:
  - type: web
    name: pavepo-auth
    env: node
    region: frankfurt
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: WEBAPP_URL
        value: https://pavepo-auth.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: pavepo-db
          property: connectionString
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ADMIN_USER_ID
        value: 5093303797
      - key: PORT
        value: 3000
databases:
  - name: pavepo-db
    databaseName: pavepo
    plan: free
